# Generated by Django 3.2 on 2023-01-20 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_ganretitle_namechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценка от 1 до 10'), django.core.validators.MaxValueValidator(10, 'Оценка от 1 до 10')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2023, 'Год не может быть больше текущего')], verbose_name='Год выпуска'),
        ),
        migrations.AlterUniqueTogether(
            name='genretitle',
            unique_together=set(),
        ),
    ]
